# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  # web:
  #   image: flaskapi
  #   build: .
  #   command: gunicorn -b 0.0.0.0:5000 flaskapi.wsgi:app
  #   env_file:
  #     - ./.flaskenv
  #   environment:
  #     - DATABASE_URI=sqlite:////db/flaskapi.db
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
  #     - CELERY_RESULT_BACKEND_URL=redis://redis
  #   volumes:
  #     - ./flaskapi:/code/flaskapi
  #     - ./db/:/db/
  #   ports:
  #     - "5000:5000"
  # rabbitmq:
  #   image: rabbitmq
  redis:
    image: redis
    ports:
      - "6379:6379"
  # celery:
  #   image: flaskapi
  #   command: "celery worker -A flaskapi.celery_app:app"
  #   env_file:
  #     - ./.flaskenv
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
  #     - CELERY_RESULT_BACKEND_URL=redis://redis
