
name: Lint test

on:
  # Run each time we push and pull requests
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        # Use the v1 tag of: https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Setup Python
        # Use the master branch of: https://github.com/actions/setup-python
        uses: actions/setup-python@master
        with:
          version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
      - name: Lint
        run: pre-commit run --all-files